#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#hello page:
#  path: /hello
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController:templateAction
#  defaults:
#    template: 'hello_page.html.twig'